# TODO (Database 접속 정보 추가)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootex?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: '0000'